export const classes = [
  {
    name: "Bárbaro",
    key: "barbarian",
    primaryRole: "Marcial",
    hitDie: 12,
    spellcastingAbilityKey: null,
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 3,
    weaponProficiencyKeys: ["simple-weapons", "martial-weapons"],
    protectionProficiencyKeys: ["light-armor", "medium-armor", "shield"],
    toolProficiencyKeys: [],
    description:
      "Combatente feroz movido por fúria, instinto e resistência física extrema.",
  },
  {
    name: "Bardo",
    key: "bard",
    primaryRole: "Suporte",
    hitDie: 8,
    spellcastingAbilityKey: "charisma",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 3,
    weaponProficiencyKeys: [
      "simple-weapons",
      "hand-crossbow",
      "longsword",
      "rapier",
      "shortsword",
    ],
    protectionProficiencyKeys: ["light-armor"],
    toolProficiencyKeys: ["musical-instrument"],
    description:
      "Artista arcano que inspira aliados, manipula emoções e transforma expressão em poder.",
  },
  {
    name: "Bruxo",
    key: "warlock",
    primaryRole: "Oculto",
    hitDie: 8,
    spellcastingAbilityKey: "charisma",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 2,
    weaponProficiencyKeys: ["simple-weapons"],
    protectionProficiencyKeys: ["light-armor"],
    toolProficiencyKeys: [],
    description:
      "Conjurador ligado a forças misteriosas, maldições, pactos e segredos arcanos perigosos.",
  },
  {
    name: "Devoto",
    key: "devotee",
    primaryRole: "Suporte",
    hitDie: 8,
    spellcastingAbilityKey: "wisdom",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 2,
    weaponProficiencyKeys: ["simple-weapons"],
    protectionProficiencyKeys: ["light-armor", "medium-armor", "shield"],
    toolProficiencyKeys: [],
    description:
      "Canaliza poder de uma fé, ideal, entidade, tradição espiritual ou força superior para curar, proteger e purificar.",
  },
  {
    name: "Druida",
    key: "druid",
    primaryRole: "Natural",
    hitDie: 8,
    spellcastingAbilityKey: "wisdom",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 2,
    weaponProficiencyKeys: [
      "club",
      "dagger",
      "dart",
      "javelin",
      "mace",
      "quarterstaff",
      "scimitar",
      "sickle",
      "sling",
      "spear",
    ],
    protectionProficiencyKeys: ["light-armor", "medium-armor", "shield"],
    toolProficiencyKeys: ["herbalism-kit"],
    description:
      "Conjurador ligado às forças naturais, mutações, animais, ciclos vitais e terrenos selvagens.",
  },
  {
    name: "Feiticeiro",
    key: "sorcerer",
    primaryRole: "Arcano",
    hitDie: 6,
    spellcastingAbilityKey: "charisma",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 2,
    weaponProficiencyKeys: [
      "dagger",
      "dart",
      "sling",
      "quarterstaff",
      "light-crossbow",
    ],
    protectionProficiencyKeys: [],
    toolProficiencyKeys: [],
    description:
      "Conjurador de magia inata, guiado por sangue, mutação, herança ou poder interior instintivo.",
  },
  {
    name: "Guerreiro",
    key: "fighter",
    primaryRole: "Marcial",
    hitDie: 10,
    spellcastingAbilityKey: null,
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 3,
    weaponProficiencyKeys: ["simple-weapons", "martial-weapons"],
    protectionProficiencyKeys: [
      "light-armor",
      "medium-armor",
      "heavy-armor",
      "shield",
    ],
    toolProficiencyKeys: [],
    description:
      "Especialista em combate, armas, armaduras, disciplina marcial e adaptação tática.",
  },
  {
    name: "Ladino",
    key: "rogue",
    primaryRole: "Especialista",
    hitDie: 8,
    spellcastingAbilityKey: null,
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 4,
    weaponProficiencyKeys: [
      "simple-weapons",
      "hand-crossbow",
      "longsword",
      "rapier",
      "shortsword",
    ],
    protectionProficiencyKeys: ["light-armor"],
    toolProficiencyKeys: ["thieves-tools"],
    description:
      "Especialista em furtividade, precisão, truques, mobilidade e ataques oportunistas.",
  },
  {
    name: "Mago",
    key: "wizard",
    primaryRole: "Arcano",
    hitDie: 6,
    spellcastingAbilityKey: "intelligence",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 2,
    weaponProficiencyKeys: [
      "dagger",
      "dart",
      "sling",
      "quarterstaff",
      "light-crossbow",
    ],
    protectionProficiencyKeys: [],
    toolProficiencyKeys: [],
    description:
      "Estudioso da magia, rituais, grimórios, fórmulas arcanas e conhecimento sobrenatural.",
  },
  {
    name: "Monge",
    key: "monk",
    primaryRole: "Marcial",
    hitDie: 8,
    spellcastingAbilityKey: null,
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 3,
    weaponProficiencyKeys: ["simple-weapons", "shortsword"],
    protectionProficiencyKeys: [],
    toolProficiencyKeys: ["artisan-tools", "musical-instrument"],
    description:
      "Combatente disciplinado que usa corpo, mente, velocidade e energia interior como armas.",
  },
  {
    name: "Juramentado",
    key: "oathbound",
    primaryRole: "Defensor",
    hitDie: 10,
    spellcastingAbilityKey: "charisma",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 2,
    weaponProficiencyKeys: ["simple-weapons", "martial-weapons"],
    protectionProficiencyKeys: [
      "light-armor",
      "medium-armor",
      "heavy-armor",
      "shield",
    ],
    toolProficiencyKeys: [],
    description:
      "Guerreiro místico sustentado por juramentos, convicções e a força de uma promessa inquebrável.",
  },
  {
    name: "Patrulheiro",
    key: "ranger",
    primaryRole: "Explorador",
    hitDie: 10,
    spellcastingAbilityKey: "wisdom",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 3,
    weaponProficiencyKeys: ["simple-weapons", "martial-weapons"],
    protectionProficiencyKeys: ["light-armor", "medium-armor", "shield"],
    toolProficiencyKeys: [],
    description:
      "Explorador, rastreador e combatente versátil treinado para sobreviver em regiões hostis.",
  },
  {
    name: "Tecnomante",
    key: "technomancer",
    primaryRole: "Tecnológico",
    hitDie: 8,
    spellcastingAbilityKey: "intelligence",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 2,
    weaponProficiencyKeys: ["simple-weapons", "firearms", "crossbows"],
    protectionProficiencyKeys: ["light-armor", "medium-armor", "shield"],
    toolProficiencyKeys: ["tinker-tools", "alchemist-supplies"],
    description:
      "Especialista em tecnologia antiga, dispositivos, engenhocas, alquimia e tecno-magia.",
  },
  {
    name: "Necromante",
    key: "necromancer",
    primaryRole: "Sombrio",
    hitDie: 6,
    spellcastingAbilityKey: "intelligence",
    subclassSelectionLevel: 3,
    classSkillChoiceCount: 2,
    weaponProficiencyKeys: ["dagger", "dart", "sling", "quarterstaff"],
    protectionProficiencyKeys: [],
    toolProficiencyKeys: [],
    description:
      "Conjurador da morte, espíritos, ossos, dreno vital, cadáveres e forças necromânticas.",
  },
] as const;
