export const classSpellAccess = [
  {
    classKey: "bard",
    spellKeys: [
      "minor-light",
      "arcane-spark",
      "mind-burst",
      "illusory-veil",
      "arcane-pulse",
      "energy-dart",
      "reactive-shield",
      "omen-mark",
      "thunder-wave",
      "spectral-blade",
      "vital-sign",
      "mist-step",
      "sudden-dread",
      "protective-echo",
      "silence-veil",
      "iron-command",
    ],
    minimumClassLevel: 1,
  },
  {
    classKey: "warlock",
    spellKeys: [
      "funeral-touch",
      "mind-burst",
      "shadow-hands",
      "illusory-veil",
      "dead-whispers",
      "dark-command",
      "omen-mark",
      "spectral-blade",
      "shock-pulse",
      "ruin-ray",
      "sudden-dread",
      "life-drain",
      "silence-veil",
      "iron-command",
      "fireball",
    ],
    minimumClassLevel: 1,
  },
  {
    classKey: "devotee",
    spellKeys: [
      "minor-light",
      "funeral-touch",
      "mend-wounds",
      "dead-whispers",
      "dark-command",
      "reactive-shield",
      "vital-sign",
      "iron-bark",
      "protective-echo",
      "repairing-hands",
      "iron-command",
    ],
    minimumClassLevel: 1,
  },
  {
    classKey: "druid",
    spellKeys: [
      "minor-light",
      "unstable-flame",
      "binding-roots",
      "mend-wounds",
      "dead-whispers",
      "vital-sign",
      "iron-bark",
      "root-snare",
      "repairing-hands",
      "ash-burst",
    ],
    minimumClassLevel: 1,
  },
  {
    classKey: "sorcerer",
    spellKeys: [
      "minor-light",
      "arcane-spark",
      "unstable-flame",
      "mind-burst",
      "arcane-pulse",
      "energy-dart",
      "reactive-shield",
      "thunder-wave",
      "shock-pulse",
      "mist-step",
      "ruin-ray",
      "interference-field",
      "ash-burst",
    ],
    minimumClassLevel: 1,
  },
  {
    classKey: "wizard",
    spellKeys: [
      "minor-light",
      "funeral-touch",
      "arcane-spark",
      "mind-burst",
      "unstable-flame",
      "shadow-hands",
      "illusory-veil",
      "arcane-pulse",
      "dead-whispers",
      "energy-dart",
      "reactive-shield",
      "binding-roots",
      "dark-command",
      "omen-mark",
      "thunder-wave",
      "spectral-blade",
      "shock-pulse",
      "shape-scrap",
      "vital-sign",
      "iron-bark",
      "mist-step",
      "ruin-ray",
      "repairing-hands",
      "sudden-dread",
      "protective-echo",
      "root-snare",
      "silence-veil",
      "life-drain",
      "interference-field",
      "iron-command",
      "ash-burst",
      "fireball",
    ],
    minimumClassLevel: 1,
  },
  {
    classKey: "oathbound",
    spellKeys: [
      "minor-light",
      "mend-wounds",
      "reactive-shield",
      "iron-bark",
      "protective-echo",
      "iron-command",
    ],
    minimumClassLevel: 2,
  },
  {
    classKey: "ranger",
    spellKeys: [
      "minor-light",
      "unstable-flame",
      "binding-roots",
      "mend-wounds",
      "vital-sign",
      "iron-bark",
      "root-snare",
    ],
    minimumClassLevel: 2,
  },
  {
    classKey: "technomancer",
    spellKeys: [
      "minor-light",
      "arcane-spark",
      "arcane-pulse",
      "energy-dart",
      "reactive-shield",
      "shock-pulse",
      "shape-scrap",
      "repairing-hands",
      "interference-field",
      "ruin-ray",
    ],
    minimumClassLevel: 2,
  },
  {
    classKey: "necromancer",
    spellKeys: [
      "funeral-touch",
      "shadow-hands",
      "mind-burst",
      "dead-whispers",
      "dark-command",
      "omen-mark",
      "illusory-veil",
      "spectral-blade",
      "vital-sign",
      "life-drain",
      "sudden-dread",
      "silence-veil",
      "putrefaction-orb",
    ],
    minimumClassLevel: 1,
  },
] as const;
