
export const equipment = [
  {
    name: "Adaga",
    key: "dagger",
    imageUrl: "/images/equipment/dagger.png",
    category: "WEAPON",
    damage: "1d4 perfurante",
    damageFormula: "1d4",
    damageType: "perfurante",
    defense: null,
    cost: "2 moedas",
    weight: 0.5,
    properties: "Leve, arremesso, acuidade",
    attackType: "MELEE",
    attackAbilityKey: "strength",
    alternativeAbilityKey: "dexterity",
    weaponGroup: "SIMPLE",
    normalRange: 6,
    longRange: 18,
    isFinesse: true,
    isThrown: true,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Lâmina curta e fácil de ocultar, comum entre viajantes, ladinos e sobreviventes urbanos.",
  },
  {
    name: "Espada Longa",
    key: "longsword",
    imageUrl: "/images/equipment/longsword.png",
    category: "WEAPON",
    damage: "1d8 cortante",
    damageFormula: "1d8",
    damageType: "cortante",
    defense: null,
    cost: "15 moedas",
    weight: 1.5,
    properties: "Versátil",
    attackType: "MELEE",
    attackAbilityKey: "strength",
    alternativeAbilityKey: null,
    weaponGroup: "MARTIAL",
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: true,
    versatileDamageFormula: "1d10",
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Arma marcial equilibrada, usada por guerreiros, juramentados e combatentes treinados.",
  },
  {
    name: "Machado Pesado",
    key: "heavy-axe",
    imageUrl: "/images/equipment/heavy-axe.png",
    category: "WEAPON",
    damage: "1d12 cortante",
    damageFormula: "1d12",
    damageType: "cortante",
    defense: null,
    cost: "30 moedas",
    weight: 3,
    properties: "Duas mãos, pesado",
    attackType: "MELEE",
    attackAbilityKey: "strength",
    alternativeAbilityKey: null,
    weaponGroup: "MARTIAL",
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: true,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Arma brutal capaz de partir madeira, osso e metal enfraquecido.",
  },
  {
    name: "Arco Curto",
    key: "shortbow",
    imageUrl: "/images/equipment/shortbow.png",
    category: "WEAPON",
    damage: "1d6 perfurante",
    damageFormula: "1d6",
    damageType: "perfurante",
    defense: null,
    cost: "25 moedas",
    weight: 1,
    properties: "Distância, duas mãos",
    attackType: "RANGED",
    attackAbilityKey: "dexterity",
    alternativeAbilityKey: null,
    weaponGroup: "SIMPLE",
    normalRange: 24,
    longRange: 96,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: true,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description: "Arma simples para caça, patrulha e combate à distância.",
  },
  {
    name: "Armadura de Couro",
    key: "leather-armor",
    imageUrl: "/images/equipment/leather-armor.png",
    category: "ARMOR",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: 1,
    cost: "10 moedas",
    weight: 2,
    properties: "Leve, proteção aplicada",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Proteção leve ativada como camada defensiva. Não substitui a roupa visual do personagem.",
  },
  {
    name: "Cota Reforçada",
    key: "reinforced-mail",
    imageUrl: "/images/equipment/reinforced-mail.png",
    category: "ARMOR",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: 3,
    cost: "50 moedas",
    weight: 8,
    properties: "Média, proteção aplicada",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Proteção reforçada com placas, anéis metálicos e peças reaproveitadas. Funciona como camada mecânica defensiva, não como roupa comum.",
  },
  {
    name: "Escudo Simples",
    key: "simple-shield",
    imageUrl: "/images/equipment/simple-shield.png",
    category: "SHIELD",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: 1,
    cost: "10 moedas",
    weight: 3,
    properties: "Uma mão, proteção ativa",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Escudo comum usado para bloquear golpes, proteger aliados e manter posição.",
  },
  {
    name: "Kit de Sobrevivência",
    key: "survival-kit",
    imageUrl: "/images/equipment/survival-kit.png",
    category: "GEAR",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "15 moedas",
    weight: 2,
    properties: "Exploração",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Conjunto básico com corda, pederneira, anzóis, lâmina pequena e suprimentos simples.",
  },
  {
    name: "Bolsa de Aventureiro",
    key: "adventurer-pouch",
    imageUrl: "/images/equipment/adventurer-pouch.png",
    category: "GEAR",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "5 moedas",
    weight: 0.5,
    properties: "Carga, organização",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Bolsa resistente para moedas, rações pequenas, mapas, ferramentas leves e objetos pessoais.",
  },
  {
    name: "Pacote de Explorador",
    key: "explorer-pack",
    imageUrl: "/images/equipment/explorer-pack.png",
    category: "GEAR",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "10 moedas",
    weight: 3,
    properties: "Exploração, viagem",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Mochila com itens básicos para viagem, acampamento e sobrevivência fora da cidade.",
  },
  {
    name: "Pé de Cabra",
    key: "crowbar",
    imageUrl: "/images/equipment/crowbar.png",
    category: "TOOL",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "2 moedas",
    weight: 2,
    properties: "Arrombamento, força",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Barra metálica simples usada para forçar portas, mover obstáculos e improvisar alavancas.",
  },
  {
    name: "Ferramentas de Ladrão",
    key: "thieves-tools",
    imageUrl: "/images/equipment/thieves-tools.png",
    category: "TOOL",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "25 moedas",
    weight: 1,
    properties: "Fechaduras, armadilhas",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Conjunto discreto de gazuas, pinças e instrumentos usados para fechaduras e mecanismos delicados.",
  },
  {
    name: "Ferramentas de Tecnomante",
    key: "technomancer-tools",
    imageUrl: "/images/equipment/technomancer-tools.png",
    category: "TOOL",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "40 moedas",
    weight: 3,
    properties: "Tecnológico, reparo",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Instrumentos usados para reparar circuitos antigos, improvisar dispositivos e manipular peças instáveis.",
  },
  {
    name: "Tônico de Campo",
    key: "field-tonic",
    imageUrl: "/images/equipment/field-tonic.png",
    category: "CONSUMABLE",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "25 moedas",
    weight: 0.2,
    properties: "Uso único, recuperação",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Mistura alquímica simples usada para recuperar fôlego e estabilizar ferimentos leves.",
  },
  {
    name: "Relíquia Quebrada",
    key: "broken-relic",
    imageUrl: "/images/equipment/broken-relic.png",
    category: "RELIC",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "Variável",
    weight: 1,
    properties: "Raro, instável, misterioso",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Fragmento de tecnologia ou magia antiga. Seu uso exato depende de estudo, risco e contexto narrativo.",
  },
    {
    name: "Martelo de Guerra",
    key: "warhammer",
    imageUrl: "/images/equipment/warhammer.png",
    category: "WEAPON",
    damage: "1d8 contundente",
    damageFormula: "1d8",
    damageType: "contundente",
    defense: null,
    cost: "15 moedas",
    weight: 2,
    properties: "Versátil",
    attackType: "MELEE",
    attackAbilityKey: "strength",
    alternativeAbilityKey: null,
    weaponGroup: "MARTIAL",
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: true,
    versatileDamageFormula: "1d10",
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Martelo pesado usado para esmagar armaduras, portas, ossos e peças enferrujadas de máquinas antigas.",
  },
  {
    name: "Lança Curta",
    key: "short-spear",
    imageUrl: "/images/equipment/short-spear.png",
    category: "WEAPON",
    damage: "1d6 perfurante",
    damageFormula: "1d6",
    damageType: "perfurante",
    defense: null,
    cost: "3 moedas",
    weight: 1.5,
    properties: "Arremesso, versátil",
    attackType: "MELEE",
    attackAbilityKey: "strength",
    alternativeAbilityKey: null,
    weaponGroup: "SIMPLE",
    normalRange: 6,
    longRange: 18,
    isFinesse: false,
    isThrown: true,
    isTwoHanded: false,
    isVersatile: true,
    versatileDamageFormula: "1d8",
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Arma simples e confiável, útil em patrulhas, caçadas e defesas improvisadas de assentamentos.",
  },
  {
    name: "Lâmina Fina",
    key: "thin-blade",
    imageUrl: "/images/equipment/thin-blade.png",
    category: "WEAPON",
    damage: "1d8 perfurante",
    damageFormula: "1d8",
    damageType: "perfurante",
    defense: null,
    cost: "25 moedas",
    weight: 1,
    properties: "Acuidade",
    attackType: "MELEE",
    attackAbilityKey: "strength",
    alternativeAbilityKey: "dexterity",
    weaponGroup: "MARTIAL",
    normalRange: null,
    longRange: null,
    isFinesse: true,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Espada estreita e precisa, usada por duelistas, nobres decadentes e assassinos de técnica refinada.",
  },
  {
    name: "Besta Leve",
    key: "light-crossbow",
    imageUrl: "/images/equipment/light-crossbow.png",
    category: "WEAPON",
    damage: "1d8 perfurante",
    damageFormula: "1d8",
    damageType: "perfurante",
    defense: null,
    cost: "25 moedas",
    weight: 2.5,
    properties: "Distância, recarga, duas mãos",
    attackType: "RANGED",
    attackAbilityKey: "dexterity",
    alternativeAbilityKey: null,
    weaponGroup: "SIMPLE",
    normalRange: 24,
    longRange: 96,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: true,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Arma de disparo confiável, comum entre guardas, caçadores e viajantes que preferem distância segura.",
  },
  {
    name: "Corrente Serrilhada",
    key: "serrated-chain",
    imageUrl: "/images/equipment/serrated-chain.png",
    category: "WEAPON",
    damage: "1d6 cortante",
    damageFormula: "1d6",
    damageType: "cortante",
    defense: null,
    cost: "20 moedas",
    weight: 2,
    properties: "Alcance, especial",
    attackType: "MELEE",
    attackAbilityKey: "strength",
    alternativeAbilityKey: null,
    weaponGroup: "MARTIAL",
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: true,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Corrente adaptada com lâminas e ganchos, usada para puxar, prender e rasgar inimigos à média distância.",
  },
   {
    name: "Escudo Torre Improvisado",
    key: "improvised-tower-shield",
    imageUrl: "/images/equipment/improvised-tower-shield.png",
    category: "SHIELD",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: 2,
    cost: "30 moedas",
    weight: 6,
    properties: "Pesado, cobertura, proteção ativa",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Grande escudo feito de placas reaproveitadas, usado para avançar sob fogo, proteger aliados e criar cobertura temporária.",
  },
    {
    name: "Kit de Demolição",
    key: "demolition-kit",
    imageUrl: "/images/equipment/demolition-kit.png",
    category: "TOOL",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "35 moedas",
    weight: 4,
    properties: "Demolição, estruturas, risco",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Ferramentas usadas para enfraquecer portas, quebrar barricadas, abrir ruínas e lidar com estruturas perigosas.",
  },
  {
    name: "Kit de Reparo de Campo",
    key: "field-repair-kit",
    imageUrl: "/images/equipment/field-repair-kit.png",
    category: "TOOL",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "30 moedas",
    weight: 2,
    properties: "Reparo, tecnologia, improviso",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Conjunto de peças, fios, grampos, ligas e pequenas ferramentas para consertos rápidos em campo.",
  },
  {
    name: "Injetor Estabilizante",
    key: "stabilizing-injector",
    imageUrl: "/images/equipment/stabilizing-injector.png",
    category: "CONSUMABLE",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "40 moedas",
    weight: 0.2,
    properties: "Uso único, estabilização, emergência",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Dose de emergência usada para estabilizar colapsos físicos, choque, exaustão ou ferimentos graves até tratamento adequado.",
  },
  {
    name: "Núcleo de Energia Fraturado",
    key: "fractured-energy-core",
    imageUrl: "/images/equipment/broken-relic.png",
    category: "RELIC",
    damage: null,
    damageFormula: null,
    damageType: null,
    defense: null,
    cost: "Variável",
    weight: 1,
    properties: "Raro, energético, instável",
    attackType: "NONE",
    attackAbilityKey: null,
    alternativeAbilityKey: null,
    weaponGroup: null,
    normalRange: null,
    longRange: null,
    isFinesse: false,
    isThrown: false,
    isTwoHanded: false,
    isVersatile: false,
    versatileDamageFormula: null,
    attackBonus: 0,
    damageBonus: 0,
    description:
      "Fragmento de uma fonte antiga de energia. Pode alimentar dispositivos, reagir a magia ou se tornar extremamente perigoso se manipulado sem cuidado.",
  },
] as const;
