export const features = [
  {
    sourceType: "ANCESTRY",
    ancestryKey: "humanis",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Adaptabilidade",
    key: "humanis-adaptability",
    description:
      "Humanis aprendem rápido, improvisam sob pressão e se adaptam a diferentes culturas, perigos e caminhos de vida.",
  },
  {
    sourceType: "ANCESTRY",
    ancestryKey: "sylvaris",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Sentidos Refinados",
    key: "sylvaris-refined-senses",
    description:
      "Sylvaris possuem percepção aguçada e sensibilidade a detalhes sutis do ambiente.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "fighter",
    subclassKey: null,
    level: 1,
    name: "Disciplina Marcial",
    key: "fighter-martial-discipline",
    description:
      "Guerreiros iniciam sua jornada com treinamento sólido em armas, armaduras e leitura de combate.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "necromancer",
    subclassKey: null,
    level: 1,
    name: "Toque Fúnebre",
    key: "necromancer-funeral-touch",
    description:
      "Necromantes aprendem a sentir, manipular e perturbar a energia que separa vida, morte e memória.",
  },
  {
    sourceType: "SUBCLASS",
    ancestryKey: null,
    classKey: "necromancer",
    subclassKey: "shepherd-of-the-dead",
    level: 3,
    name: "Voz dos Túmulos",
    key: "shepherd-of-the-dead-grave-voice",
    description:
      "Pastores dos Mortos conseguem ouvir ecos persistentes dos falecidos e usar esses sussurros como orientação.",
  },
    {
    sourceType: "ANCESTRY",
    ancestryKey: "durandir",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Resistência das Profundezas",
    key: "durandir-depth-resilience",
    description:
      "Durandir suportam pressão, escuridão, túneis instáveis e longas jornadas em ambientes subterrâneos ou confinados.",
  },
  {
    sourceType: "ANCESTRY",
    ancestryKey: "brutakar",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Corpo Imponente",
    key: "brutakar-imposing-body",
    description:
      "Brutakar possuem presença física marcante e facilidade para impor força, ocupar espaço e intimidar pela postura.",
  },
  {
    sourceType: "ANCESTRY",
    ancestryKey: "faunari",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Instinto Selvagem",
    key: "faunari-wild-instinct",
    description:
      "Faunari percebem sinais naturais, mudanças de humor animal e ameaças próximas com sensibilidade instintiva.",
  },
  {
    sourceType: "ANCESTRY",
    ancestryKey: "sinteticos",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Núcleo Artificial",
    key: "sinteticos-artificial-core",
    description:
      "Sintéticos possuem partes artificiais, memória estrutural ou resistência mecânica que os torna diferentes de organismos comuns.",
  },
  {
    sourceType: "ANCESTRY",
    ancestryKey: "minuri",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Pequena Coragem",
    key: "minuri-small-courage",
    description:
      "Minuri compensam baixa estatura com coragem, mobilidade e capacidade de agir em espaços onde outros não conseguem.",
  },
  {
    sourceType: "ANCESTRY",
    ancestryKey: "ignivar",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Brasa Interior",
    key: "ignivar-inner-ember",
    description:
      "Ignivar carregam calor interno, tolerância a ambientes quentes e uma energia emocional difícil de apagar.",
  },
  {
    sourceType: "ANCESTRY",
    ancestryKey: "yokari",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Olhar dos Espíritos",
    key: "yokari-spirit-gaze",
    description:
      "Yokari têm sensibilidade a presságios, presenças invisíveis e ecos espirituais que atravessam lugares antigos.",
  },
  {
    sourceType: "ANCESTRY",
    ancestryKey: "gnomyx",
    classKey: null,
    subclassKey: null,
    level: null,
    name: "Engenho Curioso",
    key: "gnomyx-curious-ingenuity",
    description:
      "Gnomyx desmontam, adaptam e compreendem mecanismos simples com rapidez incomum, mesmo quando a lógica parece quebrada.",
  },
    {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "barbarian",
    subclassKey: null,
    level: 1,
    name: "Fúria Primal",
    key: "barbarian-primal-rage",
    description:
      "O Bárbaro canaliza dor, instinto e violência em um estado de combate brutal que aumenta sua presença ofensiva.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "bard",
    subclassKey: null,
    level: 1,
    name: "Inspiração Errante",
    key: "bard-wandering-inspiration",
    description:
      "O Bardo transforma palavras, música e performance em impulso para aliados que precisam superar medo, dor ou dúvida.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "warlock",
    subclassKey: null,
    level: 1,
    name: "Marca Oculta",
    key: "warlock-hidden-mark",
    description:
      "O Bruxo carrega um sinal invisível de seu pacto, permitindo canalizar maldições, presságios e energia de entidade.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "devotee",
    subclassKey: null,
    level: 1,
    name: "Canalizar Convicção",
    key: "devotee-channel-conviction",
    description:
      "O Devoto usa fé, juramento ou tradição espiritual para sustentar aliados e confrontar forças que ameaçam seu ideal.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "druid",
    subclassKey: null,
    level: 1,
    name: "Vínculo Natural",
    key: "druid-natural-bond",
    description:
      "O Druida sente ciclos, mutações, terreno e sinais de vida ao redor, tratando a natureza como aliada viva.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "sorcerer",
    subclassKey: null,
    level: 1,
    name: "Fonte Instável",
    key: "sorcerer-unstable-source",
    description:
      "O Feiticeiro possui magia inata que pulsa sem pedir permissão, surgindo em explosões emocionais ou instintivas.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "rogue",
    subclassKey: null,
    level: 1,
    name: "Ataque Oportuno",
    key: "rogue-opportunistic-strike",
    description:
      "O Ladino explora distrações, ângulos e brechas para transformar precisão em vantagem letal.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "wizard",
    subclassKey: null,
    level: 1,
    name: "Grimório de Campo",
    key: "wizard-field-grimoire",
    description:
      "O Mago mantém anotações, fórmulas e teorias arcanas adaptadas para sobrevivência fora de bibliotecas seguras.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "monk",
    subclassKey: null,
    level: 1,
    name: "Disciplina Interior",
    key: "monk-inner-discipline",
    description:
      "O Monge treina corpo, respiração e foco para agir com precisão mesmo sob medo, dor ou caos.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "oathbound",
    subclassKey: null,
    level: 1,
    name: "Juramento Vivo",
    key: "oathbound-living-oath",
    description:
      "O Juramentado ancora sua força em uma promessa tão profunda que molda postura, combate e presença.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "ranger",
    subclassKey: null,
    level: 1,
    name: "Rastreador de Fronteira",
    key: "ranger-frontier-tracker",
    description:
      "O Patrulheiro lê pegadas, clima, ruínas e sinais de passagem para sobreviver onde mapas falham.",
  },
  {
    sourceType: "CLASS",
    ancestryKey: null,
    classKey: "technomancer",
    subclassKey: null,
    level: 1,
    name: "Engenharia Improvisada",
    key: "technomancer-improvised-engineering",
    description:
      "O Tecnomante adapta peças, sucata e circuitos antigos para criar soluções instáveis, úteis e perigosas.",
  },
    {
    sourceType: "SUBCLASS",
    ancestryKey: null,
    classKey: "barbarian",
    subclassKey: "collapse-fury",
    level: 3,
    name: "Rugido do Colapso",
    key: "collapse-fury-collapse-roar",
    description:
      "A Fúria do Colapso transforma trauma e violência em um rugido capaz de abalar inimigos próximos.",
  },
  {
    sourceType: "SUBCLASS",
    ancestryKey: null,
    classKey: "bard",
    subclassKey: "college-of-echoes",
    level: 3,
    name: "Memória Ressonante",
    key: "college-of-echoes-resonant-memory",
    description:
      "O Colégio dos Ecos permite recuperar fragmentos de histórias, vozes e emoções deixadas em lugares marcantes.",
  },
  {
    sourceType: "SUBCLASS",
    ancestryKey: null,
    classKey: "fighter",
    subclassKey: "weapon-master",
    level: 3,
    name: "Postura de Mestre",
    key: "weapon-master-master-stance",
    description:
      "O Mestre de Armas adota postura treinada para controlar distância, ângulo e ritmo contra inimigos armados.",
  },
  {
    sourceType: "SUBCLASS",
    ancestryKey: null,
    classKey: "technomancer",
    subclassKey: "arcane-engineer",
    level: 3,
    name: "Dispositivo Instável",
    key: "arcane-engineer-unstable-device",
    description:
      "O Engenheiro Arcano improvisa um pequeno dispositivo de campo com efeito útil, mas sempre sujeito a risco narrativo.",
  },
  {
    sourceType: "SUBCLASS",
    ancestryKey: null,
    classKey: "necromancer",
    subclassKey: "bone-reaper",
    level: 3,
    name: "Lâmina de Osso",
    key: "bone-reaper-bone-blade",
    description:
      "O Ceifador Ósseo molda ossos e energia fúnebre em lâminas temporárias para combate próximo.",
  },
] as const;
