export const skills = [
  { name: "Acrobacia", statName: "Destreza" },
  { name: "Arcanismo", statName: "Inteligência" },
  { name: "Atletismo", statName: "Força" },
  { name: "Demolição", statName: "Força" },
  { name: "Força Bruta", statName: "Força" },
  { name: "Manuseio Pesado", statName: "Força" },
  { name: "Atuação", statName: "Carisma" },
  { name: "Blefar", statName: "Carisma" },
  { name: "Furtividade", statName: "Destreza" },
  { name: "História", statName: "Inteligência" },
  { name: "Intimidação", statName: "Carisma" },
  { name: "Intuição", statName: "Sabedoria" },
  { name: "Investigação", statName: "Inteligência" },
  { name: "Lidar com Animais", statName: "Sabedoria" },
  { name: "Medicina", statName: "Sabedoria" },
  { name: "Natureza", statName: "Inteligência" },
  { name: "Percepção", statName: "Sabedoria" },
  { name: "Persuasão", statName: "Carisma" },
  { name: "Pilotagem", statName: "Destreza" },
  { name: "Prestidigitação", statName: "Destreza" },
  { name: "Religião", statName: "Inteligência" },
  { name: "Sobrevivência", statName: "Sabedoria" },
  { name: "Tática", statName: "Inteligência" },
  { name: "Tecnologia", statName: "Inteligência" },
  { name: "Ofício", statName: "Inteligência" },
] as const;
