
export const spells = [
  {
    name: "Luz Menor",
    key: "minor-light",
    level: 0,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "Toque",
    duration: "1 hora",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Cria uma pequena fonte de luz mágica em um objeto, símbolo ou ponto tocado pelo conjurador.",
  },
  {
    name: "Toque Fúnebre",
    key: "funeral-touch",
    level: 0,
    school: "NECROMANCY",
    castingTime: "1 ação",
    range: "Toque",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Canaliza energia fúnebre pelo toque, causando 1d8 necrótico e perturbando a força vital de uma criatura.",
  },
  {
    name: "Faísca Arcana",
    key: "arcane-spark",
    level: 0,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Dispara uma pequena faísca de energia arcana contra uma criatura visível, causando 1d6 energético.",
  },
  {
    name: "Rajada Mental",
    key: "mind-burst",
    level: 0,
    school: "ENCHANTMENT",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "Instantânea",
    components: "V",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Projeta uma pressão psíquica breve contra uma mente próxima, causando 1d6 psíquico.",
  },
  {
    name: "Chama Instável",
    key: "unstable-flame",
    level: 0,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Cria uma chama mutável que salta contra o alvo, causando 1d8 ígneo.",
  },
  {
    name: "Mãos Sombrias",
    key: "shadow-hands",
    level: 0,
    school: "NECROMANCY",
    castingTime: "1 ação",
    range: "9 metros",
    duration: "Instantânea",
    components: "S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Sombras em forma de mãos agarram brevemente um alvo, causando 1d6 necrótico.",
  },
  {
    name: "Véu Ilusório",
    key: "illusory-veil",
    level: 1,
    school: "ILLUSION",
    castingTime: "1 ação",
    range: "Pessoal",
    duration: "10 minutos",
    components: "V, S",
    isRitual: false,
    requiresConcentration: true,
    description:
      "Distorce a percepção ao redor do conjurador, criando uma camada sutil de disfarce, sombra ou ocultação.",
  },
  {
    name: "Pulso Arcano",
    key: "arcane-pulse",
    level: 1,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Libera um impacto de energia arcana instável contra um alvo ou ponto visível, causando 1d10 energético.",
  },
  {
    name: "Sussurros dos Mortos",
    key: "dead-whispers",
    level: 1,
    school: "NECROMANCY",
    castingTime: "1 minuto",
    range: "Pessoal",
    duration: "1 minuto",
    components: "V, S, M",
    isRitual: true,
    requiresConcentration: false,
    description:
      "Permite ouvir ecos breves deixados por uma alma, cadáver ou lugar marcado pela morte recente.",
  },
  {
    name: "Dardo de Energia",
    key: "energy-dart",
    level: 1,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "36 metros",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Cria três dardos de energia que atingem criaturas visíveis, causando 1d4+1 energético cada.",
  },
  {
    name: "Curar Ferimentos",
    key: "mend-wounds",
    level: 1,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "Toque",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Canaliza energia restauradora pelo toque, recuperando 1d8 pontos de vida.",
  },
  {
    name: "Escudo Reativo",
    key: "reactive-shield",
    level: 1,
    school: "ABJURATION",
    castingTime: "1 reação",
    range: "Pessoal",
    duration: "1 rodada",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Ergue uma barreira instantânea contra um ataque, aumentando temporariamente a defesa do conjurador.",
  },
  {
    name: "Raízes Prendentes",
    key: "binding-roots",
    level: 1,
    school: "CONJURATION",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "1 minuto",
    components: "V, S",
    isRitual: false,
    requiresConcentration: true,
    description:
      "Raízes mutadas irrompem do chão e tentam prender criaturas em uma área pequena.",
  },
  {
    name: "Comando Sombrio",
    key: "dark-command",
    level: 1,
    school: "ENCHANTMENT",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "1 rodada",
    components: "V",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Impõe uma ordem breve carregada de energia sombria a uma criatura que possa ouvir o conjurador.",
  },
  {
    name: "Marca do Agouro",
    key: "omen-mark",
    level: 1,
    school: "DIVINATION",
    castingTime: "1 ação bônus",
    range: "18 metros",
    duration: "1 minuto",
    components: "V",
    isRitual: false,
    requiresConcentration: true,
    description:
      "Marca uma criatura com um presságio visível apenas ao conjurador, facilitando ataques e leituras contra ela.",
  },
  {
    name: "Onda Trovejante",
    key: "thunder-wave",
    level: 1,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "Pessoal",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Libera uma onda de impacto sonoro ao redor do conjurador, causando 2d8 trovejante e empurrando criaturas próximas.",
  },
    {
    name: "Lâmina Espectral",
    key: "spectral-blade",
    level: 0,
    school: "NECROMANCY",
    castingTime: "1 ação",
    range: "Toque",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Forma uma lâmina translúcida por um instante, causando 1d6 necrótico ou cortante espiritual.",
  },
  {
    name: "Pulso de Choque",
    key: "shock-pulse",
    level: 0,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "9 metros",
    duration: "Instantânea",
    components: "S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Dispara um pulso elétrico curto contra uma criatura ou dispositivo, causando 1d6 elétrico.",
  },
  {
    name: "Moldar Sucata",
    key: "shape-scrap",
    level: 0,
    school: "TRANSMUTATION",
    castingTime: "1 ação",
    range: "Toque",
    duration: "Instantânea",
    components: "S, M",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Entorta, ajusta ou reposiciona uma pequena peça de metal, sucata ou mecanismo simples sem causar dano direto.",
  },
  {
    name: "Sinal Vital",
    key: "vital-sign",
    level: 0,
    school: "DIVINATION",
    castingTime: "1 ação",
    range: "9 metros",
    duration: "Instantânea",
    components: "V",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Permite perceber se uma criatura próxima está viva, morrendo, estável ou marcada por energia necromântica recente.",
  },
  {
    name: "Casca de Ferro",
    key: "iron-bark",
    level: 1,
    school: "ABJURATION",
    castingTime: "1 ação",
    range: "Toque",
    duration: "1 minuto",
    components: "V, S",
    isRitual: false,
    requiresConcentration: true,
    description:
      "Reveste pele, roupa ou proteção aplicada com rigidez temporária, concedendo defesa narrativa contra impactos leves.",
  },
  {
    name: "Passo Nebuloso",
    key: "mist-step",
    level: 1,
    school: "CONJURATION",
    castingTime: "1 ação bônus",
    range: "Pessoal",
    duration: "Instantânea",
    components: "V",
    isRitual: false,
    requiresConcentration: false,
    description:
      "O conjurador se dissolve em névoa curta e reaparece em um ponto visível próximo.",
  },
  {
    name: "Raio de Ruína",
    key: "ruin-ray",
    level: 1,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "24 metros",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Dispara energia corrosiva de colapso contra um alvo, causando 2d6 energético.",
  },
  {
    name: "Mãos Reparadoras",
    key: "repairing-hands",
    level: 1,
    school: "TRANSMUTATION",
    castingTime: "1 ação",
    range: "Toque",
    duration: "Instantânea",
    components: "V, S, M",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Repara rachaduras, encaixes e danos leves em objeto, ferramenta, proteção aplicada ou dispositivo simples.",
  },
  {
    name: "Medo Súbito",
    key: "sudden-dread",
    level: 1,
    school: "ENCHANTMENT",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "1 rodada",
    components: "V",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Projeta uma visão breve de perigo inevitável, causando hesitação e pânico momentâneo em uma criatura.",
  },
  {
    name: "Eco Protetor",
    key: "protective-echo",
    level: 1,
    school: "ABJURATION",
    castingTime: "1 reação",
    range: "9 metros",
    duration: "Instantânea",
    components: "V",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Um eco arcano reduz o impacto de um golpe contra uma criatura próxima, amortecendo parte do dano recebido.",
  },
  {
    name: "Armadilha de Raízes",
    key: "root-snare",
    level: 2,
    school: "CONJURATION",
    castingTime: "1 ação",
    range: "24 metros",
    duration: "1 minuto",
    components: "V, S",
    isRitual: false,
    requiresConcentration: true,
    description:
      "Raízes, cabos ou fibras mutadas prendem uma área, dificultando movimento e derrubando criaturas descuidadas.",
  },
  {
    name: "Véu de Silêncio",
    key: "silence-veil",
    level: 2,
    school: "ILLUSION",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "10 minutos",
    components: "S",
    isRitual: false,
    requiresConcentration: true,
    description:
      "Cria uma zona abafada onde sons se perdem, passos são suavizados e palavras parecem distantes.",
  },
  {
    name: "Dreno Vital",
    key: "life-drain",
    level: 2,
    school: "NECROMANCY",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Arranca energia vital de uma criatura, causando 3d6 necrótico e fortalecendo brevemente o conjurador.",
  },
  {
    name: "Campo de Interferência",
    key: "interference-field",
    level: 2,
    school: "ABJURATION",
    castingTime: "1 ação",
    range: "Pessoal",
    duration: "1 minuto",
    components: "V, S, M",
    isRitual: false,
    requiresConcentration: true,
    description:
      "Um campo instável distorce projéteis, sensores, relíquias e pequenos efeitos mágicos ao redor do conjurador.",
  },
  {
    name: "Comando de Ferro",
    key: "iron-command",
    level: 2,
    school: "ENCHANTMENT",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "1 minuto",
    components: "V",
    isRitual: false,
    requiresConcentration: true,
    description:
      "A voz do conjurador impõe disciplina sobrenatural, obrigando uma criatura a hesitar, recuar ou manter posição.",
  },
  {
    name: "Explosão de Cinzas",
    key: "ash-burst",
    level: 2,
    school: "EVOCATION",
    castingTime: "1 ação",
    range: "18 metros",
    duration: "Instantânea",
    components: "V, S",
    isRitual: false,
    requiresConcentration: false,
    description:
      "Uma nuvem explosiva de cinzas quentes e energia instável causa 3d8 ígneo em uma pequena área.",
  },
] as const;
